# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Borbit
email: borbit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Borbit is a Software Company, focused on iOS app development for iPhone and iPad devices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://borbit.io" # the base hostname & protocol for your site, e.g. http://example.com

author: "Gastón Borba"

twitter:
  username: horacioborba

twitter_username: horacioborba
twitter_link: https://twitter.com/horacioborba
github_link: https://github.com/gastonborba
linkedin_link: https://www.linkedin.com/in/gast%C3%B3n-borba-6567822a/
skype_link: skype:gastonborba_2?chat

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

excerpt_separator: <!--more-->

# Pagination 
paginate: 5
paginate_path: "/blog/page:num/"

# Disqus
disqus:
  shortname: borbit

# Collections
collections:
  projects:
    output: true

google_analytics: UA-81281254-3


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
